# -*- coding: utf-8 -*-
"""21032_AishwaryaGupta_Modules and Packages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UrrjdLKttYnhWuCRKTlbD6-UFSlwXm_d

##Question 1 :
Take a date as input and find what the day is on that date.
#####Input Format: A single line of input containing the space separated month, day and year, respectively, in MM DD YYYY format.
#####Output Format: Output the correct day in capital letters.
#####Sample Input: 08 05 2015
#####Sample Output: WEDNESDAY
#####Explanation: The day on August 5th 2015 was WEDNESDAY.
#####Reference link : https://docs.python.org/3/library/calendar.html
"""

from statistics import mean,harmonic_mean,median_low,median_high,mode
from datetime import datetime,timedelta

# !pip install datetime

month,day,year=map(int,input("Enter date in MM DD YYYY format: ").strip().split(" "))

day_out=datetime(year,day,month).strftime("%A").upper()

print(day_out)

"""##Question 2 :
Take a list of integers as an input and find mean(), harmonic_mean(), median_low(), median_high() and mode().
#####Reference link : https://docs.python.org/3/library/statistics.html#module-statistics
"""

# Write your solution here.
# !pip install statistics

int_in=list(map(int,input("Enter list of integers (space separated): ").strip().split()))

mean_out=mean(int_in)
hmean_out=harmonic_mean(int_in)
med_low=median_low(int_in)
med_high=median_high(int_in)
try:
  mod=mode(int_in)
except :
  mod="no unique mode; found more than 1 equally common values"

print(" Mean:{}\n Harmonic Mean:{}\n Median High:{}\n Median Low:{}\n Mode:{}\n".format(mean_out,hmean_out,med_low,med_high,mod))

"""##Question 3 :
Take a date as an input and display following DateTime formats.
#####a) Current date and time
#####b) Current year
#####c) Month of year
#####d) Week number of the year
#####e) Weekday of the week
#####f) Day of year
#####g) Day of the month
#####h) Day of week

Reference link : https://docs.python.org/3/library/datetime.html#module-datetime
"""

# Write your solution here.

day,month,year=map(int,input("Enter Date as DD MM YYYY: ").strip().split())

x=datetime(year,month,day)
today=datetime.now()
print("Current Date and time: ",today)
print("Current year: ",today.strftime("%Y"))
print("Month of year: ",today.strftime("%B"))
print("Week number of the year: ",today.strftime("%U"))
print("Weekday of the week: ",today.strftime("%w"))
print("Day of year: ",today.strftime("%j"))
print("Day of the month: ",today.strftime("%d"))
print("Day of week: ",today.strftime("%A"))

print("\nFor",x,": ")
print("Year: ",x.strftime("%Y"))
print("Month of year: ",x.strftime("%B"))
print("Week number of the year: ",x.strftime("%U"))
print("Weekday of the week: ",x.strftime("%w"))
print("Day of year: ",x.strftime("%j"))
print("Day of the month: ",x.strftime("%d"))
print("Day of week: ",x.strftime("%A"))

"""##Question 4 :
Write a code to convert a string to datetime.
#####Sample input : Jan 1 2014 2:43PM
#####Sample Output : 2014-07-01 14:43:00
"""

# Write your solution here.
datetime_in=input("Enter Date & Time: ").strip()
datetime_out = datetime.strptime(datetime_in, '%b %d %Y %I:%M%p')
print(datetime_out)

"""##Question 5 :
Write a code to subtract five days from current date.
#####Sample Current Date : 2015-06-22
#####5 days before Current Date : 2015-06-17
"""

# Write your solution here.
x=datetime.today()
print("Current Date: ",x.date())
d = x - timedelta(days=5)
print("5 days before Current Date: ",d.date())

"""##Question 6 :
Write a code that accepts a comma separated sequence of words as input and prints the unique words in sorted form (alphanumerically).
#####Sample Words : red, white, black, red, green, black
#####Expected Result : black, green, red, white

Reference link : https://docs.python.org/3/library/string.html#module-string
"""

# Write your solution here.
list_out=[]
string_list=list(input("Enter comma separated words : ").split(","))

# Remove white spaces
string_list=[i.strip() for i in string_list]
# Append to new list if not already present
[i and list_out.append(i) for i in string_list if i not in list_out]

print(sorted(list_out))

"""##Question 7 :
Create a module file with three functions -
#####a) To return number of uppercase letters - def uppercase(str):
#####b) To return number of lowercase letters - def lowercase(str):
#####c) To return number of vowels - def vowel(str):

#####Save the module file as modstring.py  
#####Write a code that takes a string as an input. Import the modstring.py module and execute all three functions.

#####Reference link (To import module file in Colaboratory) : https://www.pingshiuanchua.com/blog/post/importing-your-own-python-module-or-python-file-in-colaboratory
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/My Drive/"Colab Notebooks"')

from modstring import *

str_in=input("Enter a string: ").strip()

print("Uppercase Letters: ",uppercase(str_in))
print("Lowercase Letters: ",lowercase(str_in))
print("Vowels: ",vowel(str_in))

"""##Question 8 :
Create a module file with three functions -
#####a) Write Fibonacci series up to n - def fibonacci(n):
#####b) Find if n is even or odd number - def evenodd(n):
#####c) Find if n is a prime number - def prime(n):

#####Save the module file as modinteger.py  
#####Write a code that takes an integer as an input. Import the modinteger.py module and execute all three functions.

#####Reference link (To import module file in Colaboratory) : https://www.pingshiuanchua.com/blog/post/importing-your-own-python-module-or-python-file-in-colaboratory
"""

# Write your solution here.

drive.mount("/content/drive", force_remount=True)
from modinteger import *

n=int(input("Enter an integer: ").strip())

print("Febonacci Series:",fibonacci(n) )
print("Even or Odd: ",evenodd(n))
print("Is a Prime Number: ",prime(n))



